# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      # Runs a set of commands using the runners shell
      - name: tests
        run: |
          cd $GITHUB_WORKSPACE
          echo 'installing root npm packages...'
          npm i
          echo 'building soda...'
          make build
          cd $GITHUB_WORKSPACE/examples/
          echo 'installing example npm packages...'
          npm i
          ./build-test.sh
          cd $GITHUB_WORKSPACE/tests/
          echo 'installing test npm packages...'
          npm i
          cd $GITHUB_WORKSPACE/tests/test-apps/
          echo 'building test apps...'
          make build
          echo 'serving test apps...'
          python3 -m http.server -d build/ -b localhost 8080 &
          sleep 5
          echo 'running tests...'
          cd $GITHUB_WORKSPACE/tests/scripts/
          python3 run-tests.py
